#! /usr/bin/env python

import json
import os
import re
import sys

def perform_env_overrides(override_string):
    """ overwrite env variable VAR if {override_string}VAR is set  """
    overridden_vars = []
    for var in os.environ.keys():
        if var.startswith(override_string):
            target_var = re.sub(override_string, '', var)
            os.environ[target_var] = os.environ[var]
            overridden_vars.append(var)
    return overridden_vars

def exec_proggie(program, args=[]):
    os.execvp(program, args)

if __name__ == '__main__':
    override_string = 'OVERRIDE_'
    overridden_vars = perform_env_overrides(override_string)
    for var in overridden_vars:
      target_var = re.sub(override_string, '', var)
      print "overriding var {}".format(target_var)

    exec_proggie(sys.argv[1], args=sys.argv[1:])
